### ISSUE TITLE
Re: "...modifications of a SalHack derivative"

### ISSUE THREAD

**Issue by rThirtyThree** [Crystallinqq/PyroClientReup#4]
I was just wondering under what basis is Pyro a Salhack derivative?

**Comment by Crystallinqq** [comment]
Many modules are from SalHack/spidermod.

**Comment by Glizzwaldd** [comment]
@Crystallinqq just because they use parts (if they even do ) of an open source repository it doesnt mean that its a derrivative. Under that logic then everything made in Python and Ruby is free for the public to post the source code of a claim it is their own code. This would probably include Facebook's products, Amazons products, Netflix's products, Google's products, etc.

So what differentiates pyro from using code from an open source repo from being a derivative?

**Comment by Glizzwaldd** [comment]
also did you file a DMCA counternotice or did you just reupload it?

**Comment by Crystallinqq** [comment]
Both. However my counternotice hasn’t been processed. Parts of the base are also from SalHack.
